[package]
name = "nano_pay"
version = "0.1.0"
authors = ["Daan Lubbers (Daan4@users.noreply.github.com)"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake2b_simd = "0.5.11"
rand = "0.8.4"
byteorder = "1.4.3"
