# wallet seed, change this
wallet_seed = "0000000000000000000000000000000000000000000000000000000000000000"

# node address
node_address = "127.0.0.1"

# node rpc port
node_rpc_port = 17076

# node websocket port
node_ws_port = 17078

# transaction timeout in seconds
transaction_timeout = 300

# representative, change this
representative = "nano_1b9wguhh39at8qtm93oghd6r4f4ubk7zmqc9oi5ape6yyz4s1gamuwn3jjit"
