# wallet seed, change this
wallet_seed = "0000000000000000000000000000000000000000000000000000000000000000"

# node address
node_address = "127.0.0.1"

# node rpc port
node_rpc_port = 17076

# work server address
work_address = "127.0.0.1"

# work server port
work_port = 1111

# transaction timeout in seconds
transaction_timeout = 300

# representative
representative = ""
