wallet_seed = "907933879BCBA2F7C92E3A03A59255F3BC3B72C4AD49E7A57B48B7DF5F4ADD20"

# node IP address
node_address = "127.0.0.1"

# node rpc port
node_rpc_port = 17076

# node websocket port
node_ws_port = 17078

# transaction timeout in seconds
transaction_timeout = 10

# representative
representative = "nano_1b9wguhh39at8qtm93oghd6r4f4ubk7zmqc9oi5ape6yyz4s1gamuwn3jjit"
